//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Appointments = new HashSet<Appointments>();
            this.JobOwners = new HashSet<JobOwners>();
            this.Jobs = new HashSet<Jobs>();
            this.Services = new HashSet<Services>();
            this.WorkingTimes = new HashSet<WorkingTimes>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
        public bool isJobOwner { get; set; }
        public bool isWorker { get; set; }
        public bool isAdmin { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public int JobId { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<JobOwners> JobOwners { get; set; }
        public virtual ICollection<Jobs> Jobs { get; set; }
        public virtual Jobs Jobs1 { get; set; }
        public virtual ICollection<Services> Services { get; set; }
        public virtual ICollection<WorkingTimes> WorkingTimes { get; set; }
    }
}
